# Generated by Django 3.2.6 on 2021-08-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20210814_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
